### ISSUE TITLE
Create a Hello-World React client

### ISSUE THREAD

**Issue by chichiwang** [chichiwang/exercise-js#17]
Create a Hello-World React client with routing, TypeScript, and bundling.

Acceptance Criteria:
* A React client exists that
  * Is server-side rendered
  * Uses TypeScript
  * Is bundled into distributable artifacts
    * Git-ignored
  * Renders a simple Hello, React! with a base application and a single component

**Comment by chichiwang** [comment]
## TODOS
- [x] Modularize webpack configs to account for client and server configs (in the future, for production as well, once we determine what's necessary there
- [x] Create script to update snapshots in `package.json`, something like a `test:snapshot`
- [x] Move `client/app.tsx` to a new `app/app.tsx` directory, and update Aliases. `app/` directory should contain the top-level markup and router components.
- [ ] ~Investigate the feasibility of a `config/` directory to hold all project configurations~
- [ ] ~Create a `/docs` directory to document the project configurations and instructions~
  - [ ] ~Document how to run tests and update snapshots (including usage of `npm run test -- -u`)~

**Comment by chichiwang** [comment]
Housing development tooling configurations in their own directory is not advised, as these tools expect their configurations in the project root. Removing the TODO item for this.

**Comment by chichiwang** [comment]
Documentation for the project has been split off into its own issue (#29) and will not be addressed in this one. Removing the TODO items for this.

**Comment by chichiwang** [comment]
Acceptance Criteria met, task completed.
